version: 2.1
commands: 
  check-skippable-pr:
    steps:
      - run: apk add --no-cache bash curl jq
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "What pull request user name is?"
          command: echo ${CIRCLE_PROJECT_USERNAME}
      - run:
          name: "Set pull request number variable"
          command: echo 'export PR_NUM="${CIRCLE_PULL_REQUEST##*/}"' >> $BASH_ENV
      - run:
          name: "Print PR_NUM"
          command: echo ${PR_NUM}
      - run:
          name: "What project username is?"
          command: echo ${CIRCLE_PROJECT_USERNAME}
      - run:
          name: "What circle build num is?"
          command: echo ${CIRCLE_BUILD_NUM}
jobs:
  check-skippable-pr:
    docker:
      - image: alpine:3.7
    steps:
      - check-skippable-pr
workflows:
  check-skippable:
    jobs:
      - check-skippable-pr

