version: 2.1
orbs:
  bye-github-draft: whyayen/bye-github-draft@0.0.1
jobs:
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
workflows:
  check-skippable:
    jobs:
      - bye-github-draft/check-skippable-pr
      - test:
          requires:
            - bye-github-draft/check-skippable-pr

